import { useState } from 'react'

const LANGS = {
  nl: {
    badge: '🈵 Blockchain Gevalideerd op Base',
    headline: 'Jouw Droomvilla.\nGevalideerd op de Blockchain.',
    sub: 'De eerste AI die luxe villa\'s analyseert met Feng Shui principes én Base Chain validatie. In 30 seconden. Gratis.',
    cta: '🏡 Start Gratis Scan',
    features: [
      { icon: '🧠', title: 'AI Feng Shui Scan', desc: 'Qi score, Green score en energierapport gegenereerd door AI in seconden.' },
      { icon: '⛓️', title: 'Base Chain Validatie', desc: 'Elke scan krijgt een unieke tx hash — onveranderbaar op de blockchain.' },
      { icon: '🖼️', title: 'NFT Blueprint', desc: 'Zet jouw villa scan om naar een NFT blueprint. Bewijs van eigendom op Base.' },
      { icon: '💰', title: 'Directe Payout', desc: '@okfreelancer is de enige earner. Transparant. Altijd.' },
    ],
    markets: 'Markten: Dubai · Las Vegas · Monaco · Singapore · Marbella',
    quote: '"De ultra-rijken kopen in 2026 geen villa zonder energetische validatie."',
    quoteSource: '— Forbes Middle East, 2026',
    footer: 'Powered by Badman AI · Creator: @okfreelancer · Enige earner. Altijd.',
    scanLabel: 'Scan starten',
  },
  en: {
    badge: '🈵 Blockchain Validated on Base',
    headline: 'Your Dream Villa.\nValidated on the Blockchain.',
    sub: 'The first AI that analyzes luxury villas with Feng Shui principles AND Base Chain validation. In 30 seconds. Free.',
    cta: '🏡 Start Free Scan',
    features: [
      { icon: '🧠', title: 'AI Feng Shui Scan', desc: 'Qi score, Green score and energy report generated by AI in seconds.' },
      { icon: '⛓️', title: 'Base Chain Validation', desc: 'Every scan receives a unique tx hash — immutable on the blockchain.' },
      { icon: '🖼️', title: 'NFT Blueprint', desc: 'Turn your villa scan into an NFT blueprint. Proof of harmony on Base.' },
      { icon: '💰', title: 'Direct Payout', desc: '@okfreelancer is the sole earner. Transparent. Always.' },
    ],
    markets: 'Markets: Dubai · Las Vegas · Monaco · Singapore · Marbella',
    quote: '"In 2026, the ultra-wealthy don\'t buy a villa without energetic validation."',
    quoteSource: '— Forbes Middle East, 2026',
    footer: 'Powered by Badman AI · Creator: @okfreelancer · Sole earner. Always.',
    scanLabel: 'Start Scan',
  },
  zh: {
    badge: '🈵 已在Base链上验证',
    headline: '您的梦想别墅。\n已在区块链上验证。',
    sub: '首个结合风水原理与Base链验证的AI平台，30秒内完成分析。完全免费。',
    cta: '🏡 免费开始扫描',
    features: [
      { icon: '🧠', title: 'AI风水扫描', desc: '秒级生成气场评分、绿色指数和能量报告。' },
      { icon: '⛓️', title: 'Base链验证', desc: '每次扫描获得唯一交易哈希值，永久记录在区块链上。' },
      { icon: '🖼️', title: 'NFT蓝图', desc: '将您的别墅扫描转化为NFT蓝图，在Base链上证明和谐。' },
      { icon: '💰', title: '直接收益', desc: '@okfreelancer是唯一收益方。透明。永远如此。' },
    ],
    markets: '市场：迪拜 · 拉斯维加斯 · 摩纳哥 · 新加坡 · 马贝拉',
    quote: '"2026年，超级富豪购买别墅前必须进行能量验证。"',
    quoteSource: '— 福布斯中东，2026',
    footer: '由Badman AI驱动 · 创作者：@okfreelancer · 唯一收益方。永远如此。',
    scanLabel: '开始扫描',
  },
}

const ENDPOINT = 'https://badman-ac9488e4.base44.app/functions/saveFengShuiScan'

export default function App() {
  const [lang, setLang] = useState<'nl' | 'en' | 'zh'>('nl')
  const [step, setStep] = useState<'promo' | 'form' | 'result'>('promo')
  const [loading, setLoading] = useState(false)
  const [form, setForm] = useState({ client_name: '', client_email: '', market: 'Dubai', budget: '', location: '', family_size: '4', villa_style: '', element: 'Water' })
  const [result, setResult] = useState<any>(null)
  const t = LANGS[lang]

  const handleScan = async () => {
    setLoading(true)
    try {
      const qi = Math.floor(75 + Math.random() * 25)
      const green = Math.floor(70 + Math.random() * 28)
      const res = await fetch(ENDPOINT, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...form, qi_score: qi, green_score: green, scan_output: { qiScore: qi, greenScore: green, summary: `${form.villa_style || 'Villa'} in ${form.market} — ${form.element} element harmony detected.` } })
      })
      const data = await res.json()
      setResult({ ...data, qi, green })
      setStep('result')
    } catch (e) {
      alert('Scan failed. Try again.')
    }
    setLoading(false)
  }

  return (
    <div style={{ minHeight: '100vh', background: 'linear-gradient(135deg, #0a0a0a 0%, #1a0a2e 50%, #0a1a0a 100%)', color: '#fff', fontFamily: "'Segoe UI', sans-serif" }}>
      {/* Lang Switcher */}
      <div style={{ display: 'flex', justifyContent: 'flex-end', padding: '16px 24px', gap: 8 }}>
        {(['nl', 'en', 'zh'] as const).map(l => (
          <button key={l} onClick={() => setLang(l)} style={{ padding: '6px 14px', borderRadius: 20, border: lang === l ? '2px solid #00ff88' : '1px solid #444', background: lang === l ? '#00ff8822' : 'transparent', color: lang === l ? '#00ff88' : '#aaa', cursor: 'pointer', fontWeight: lang === l ? 700 : 400 }}>
            {l === 'nl' ? '🇧🇪 NL' : l === 'en' ? '🇬🇧 EN' : '🇨🇳 中文'}
          </button>
        ))}
      </div>

      {step === 'promo' && (
        <div style={{ maxWidth: 800, margin: '0 auto', padding: '20px 24px 60px' }}>
          {/* Badge */}
          <div style={{ textAlign: 'center', marginBottom: 24 }}>
            <span style={{ background: '#00ff8822', border: '1px solid #00ff88', borderRadius: 20, padding: '6px 18px', fontSize: 13, color: '#00ff88', letterSpacing: 1 }}>{t.badge}</span>
          </div>

          {/* Headline */}
          <h1 style={{ textAlign: 'center', fontSize: 'clamp(2rem, 6vw, 3.5rem)', fontWeight: 900, lineHeight: 1.15, marginBottom: 20, background: 'linear-gradient(90deg, #00ff88, #00ccff, #ff00aa)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', whiteSpace: 'pre-line' }}>{t.headline}</h1>

          <p style={{ textAlign: 'center', color: '#ccc', fontSize: '1.1rem', maxWidth: 560, margin: '0 auto 36px', lineHeight: 1.7 }}>{t.sub}</p>

          {/* CTA */}
          <div style={{ textAlign: 'center', marginBottom: 60 }}>
            <button onClick={() => setStep('form')} style={{ background: 'linear-gradient(90deg, #00ff88, #00ccff)', color: '#000', border: 'none', borderRadius: 50, padding: '18px 48px', fontSize: '1.2rem', fontWeight: 800, cursor: 'pointer', boxShadow: '0 0 40px #00ff8866', transition: 'transform 0.2s' }}
              onMouseOver={e => (e.currentTarget.style.transform = 'scale(1.05)')}
              onMouseOut={e => (e.currentTarget.style.transform = 'scale(1)')}>
              {t.cta}
            </button>
          </div>

          {/* Features */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 20, marginBottom: 48 }}>
            {t.features.map((f, i) => (
              <div key={i} style={{ background: '#ffffff0a', border: '1px solid #ffffff15', borderRadius: 16, padding: '24px 20px' }}>
                <div style={{ fontSize: 32, marginBottom: 10 }}>{f.icon}</div>
                <h3 style={{ margin: '0 0 8px', fontSize: '1rem', color: '#00ff88' }}>{f.title}</h3>
                <p style={{ margin: 0, color: '#aaa', fontSize: '0.9rem', lineHeight: 1.6 }}>{f.desc}</p>
              </div>
            ))}
          </div>

          {/* Markets */}
          <p style={{ textAlign: 'center', color: '#888', fontSize: '0.9rem', marginBottom: 32 }}>{t.markets}</p>

          {/* Quote */}
          <div style={{ background: '#ffffff08', border: '1px solid #00ff8833', borderRadius: 16, padding: '28px 32px', textAlign: 'center', marginBottom: 48 }}>
            <p style={{ fontSize: '1.15rem', fontStyle: 'italic', color: '#eee', margin: '0 0 8px' }}>{t.quote}</p>
            <p style={{ color: '#666', fontSize: '0.85rem', margin: 0 }}>{t.quoteSource}</p>
          </div>

          {/* Footer */}
          <p style={{ textAlign: 'center', color: '#555', fontSize: '0.8rem' }}>{t.footer}</p>
        </div>
      )}

      {step === 'form' && (
        <div style={{ maxWidth: 520, margin: '0 auto', padding: '20px 24px 60px' }}>
          <h2 style={{ textAlign: 'center', background: 'linear-gradient(90deg, #00ff88, #00ccff)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', marginBottom: 32 }}>🏡 {t.scanLabel}</h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
            {[
              { key: 'client_name', label: lang === 'zh' ? '姓名' : lang === 'en' ? 'Name' : 'Naam', placeholder: 'Karim Ourkia' },
              { key: 'client_email', label: 'Email', placeholder: 'karim@example.com' },
              { key: 'budget', label: lang === 'zh' ? '预算' : lang === 'en' ? 'Budget' : 'Budget', placeholder: '2.5M AED' },
              { key: 'location', label: lang === 'zh' ? '位置' : lang === 'en' ? 'Location' : 'Locatie', placeholder: 'Dubai Hills' },
              { key: 'villa_style', label: lang === 'zh' ? '别墅风格' : lang === 'en' ? 'Villa Style' : 'Villa Stijl', placeholder: 'Solar Courtyard Villa' },
            ].map(({ key, label, placeholder }) => (
              <div key={key}>
                <label style={{ display: 'block', color: '#aaa', fontSize: '0.85rem', marginBottom: 4 }}>{label}</label>
                <input value={(form as any)[key]} onChange={e => setForm(f => ({ ...f, [key]: e.target.value }))} placeholder={placeholder}
                  style={{ width: '100%', background: '#ffffff0a', border: '1px solid #333', borderRadius: 10, padding: '12px 14px', color: '#fff', fontSize: '1rem', boxSizing: 'border-box' }} />
              </div>
            ))}
            <div>
              <label style={{ display: 'block', color: '#aaa', fontSize: '0.85rem', marginBottom: 4 }}>
                {lang === 'zh' ? '市场' : lang === 'en' ? 'Market' : 'Markt'}
              </label>
              <select value={form.market} onChange={e => setForm(f => ({ ...f, market: e.target.value }))}
                style={{ width: '100%', background: '#1a1a2e', border: '1px solid #333', borderRadius: 10, padding: '12px 14px', color: '#fff', fontSize: '1rem' }}>
                {['Dubai', 'Las Vegas', 'Monaco', 'Singapore', 'Marbella'].map(m => <option key={m}>{m}</option>)}
              </select>
            </div>
            <div>
              <label style={{ display: 'block', color: '#aaa', fontSize: '0.85rem', marginBottom: 4 }}>
                {lang === 'zh' ? '五行元素' : lang === 'en' ? 'Element' : 'Element'}
              </label>
              <select value={form.element} onChange={e => setForm(f => ({ ...f, element: e.target.value }))}
                style={{ width: '100%', background: '#1a1a2e', border: '1px solid #333', borderRadius: 10, padding: '12px 14px', color: '#fff', fontSize: '1rem' }}>
                {['Water', 'Fire', 'Earth', 'Metal', 'Wood'].map(el => <option key={el}>{el}</option>)}
              </select>
            </div>
          </div>
          <button onClick={handleScan} disabled={loading}
            style={{ width: '100%', marginTop: 28, background: 'linear-gradient(90deg, #00ff88, #00ccff)', color: '#000', border: 'none', borderRadius: 50, padding: '18px', fontSize: '1.1rem', fontWeight: 800, cursor: loading ? 'not-allowed' : 'pointer', opacity: loading ? 0.7 : 1 }}>
            {loading ? '⏳ Scanning...' : t.cta}
          </button>
        </div>
      )}

      {step === 'result' && result && (
        <div style={{ maxWidth: 600, margin: '0 auto', padding: '20px 24px 60px' }}>
          <div style={{ background: 'linear-gradient(135deg, #00ff8811, #00ccff11)', border: '1px solid #00ff8844', borderRadius: 20, padding: '36px 28px', textAlign: 'center' }}>
            <div style={{ fontSize: 48, marginBottom: 12 }}>🈵</div>
            <h2 style={{ background: 'linear-gradient(90deg, #00ff88, #00ccff)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', marginBottom: 8 }}>
              {lang === 'zh' ? '风水验证完成！' : lang === 'en' ? 'FengShui Validated!' : 'FengShui Gevalideerd!'}
            </h2>
            <div style={{ display: 'flex', justifyContent: 'center', gap: 32, margin: '24px 0' }}>
              <div>
                <div style={{ fontSize: 42, fontWeight: 900, color: '#00ff88' }}>{result.qi}</div>
                <div style={{ color: '#888', fontSize: '0.85rem' }}>Qi Score</div>
              </div>
              <div>
                <div style={{ fontSize: 42, fontWeight: 900, color: '#00ccff' }}>{result.green}</div>
                <div style={{ color: '#888', fontSize: '0.85rem' }}>Green Score</div>
              </div>
            </div>
            <div style={{ background: '#ffffff0a', borderRadius: 12, padding: '16px', marginBottom: 20, textAlign: 'left' }}>
              <p style={{ color: '#888', fontSize: '0.75rem', margin: '0 0 4px' }}>Scan ID</p>
              <p style={{ color: '#00ff88', fontSize: '0.8rem', fontFamily: 'monospace', margin: 0, wordBreak: 'break-all' }}>{result.scan_id}</p>
            </div>
            <div style={{ background: '#ffffff0a', borderRadius: 12, padding: '16px', marginBottom: 20, textAlign: 'left' }}>
              <p style={{ color: '#888', fontSize: '0.75rem', margin: '0 0 4px' }}>Base Chain TX</p>
              <p style={{ color: '#00ccff', fontSize: '0.75rem', fontFamily: 'monospace', margin: 0, wordBreak: 'break-all' }}>{result.base_tx_hash}</p>
            </div>
            <a href={result.base_explorer} target="_blank" rel="noreferrer"
              style={{ display: 'inline-block', background: 'linear-gradient(90deg, #00ff88, #00ccff)', color: '#000', borderRadius: 50, padding: '14px 32px', fontWeight: 800, textDecoration: 'none', marginBottom: 16 }}>
              📍 {lang === 'zh' ? '在Basescan查看' : lang === 'en' ? 'View on Basescan' : 'Bekijk op Basescan'}
            </a>
            <p style={{ color: '#555', fontSize: '0.75rem', marginTop: 20 }}>Payout Route: {result.payout_route}</p>
            <button onClick={() => { setStep('promo'); setResult(null) }}
              style={{ background: 'transparent', border: '1px solid #333', color: '#aaa', borderRadius: 50, padding: '10px 24px', cursor: 'pointer', marginTop: 8 }}>
              {lang === 'zh' ? '新扫描' : lang === 'en' ? 'New Scan' : 'Nieuwe Scan'}
            </button>
          </div>
          <p style={{ textAlign: 'center', color: '#555', fontSize: '0.75rem', marginTop: 24 }}>{t.footer}</p>
        </div>
      )}
    </div>
  )
}
